/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminAuditLogRouteImport } from './routes/_admin/admin.audit-log'
import { Route as AdminAdminCauseListSourcesRouteImport } from './routes/_admin/admin.cause-list-sources'
import { Route as AdminAdminContactRequestsRouteImport } from './routes/_admin/admin.contact-requests'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAssistantRouteImport } from './routes/_authenticated/app.assistant'
import { Route as AuthenticatedAppAuditLogRouteImport } from './routes/_authenticated/app.audit-log'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app.billing'
import { Route as AuthenticatedAppCasesRouteImport } from './routes/_authenticated/app.cases'
import { Route as AuthenticatedAppCauseListRouteImport } from './routes/_authenticated/app.cause-list'
import { Route as AuthenticatedAppClientsRouteImport } from './routes/_authenticated/app.clients'
import { Route as AuthenticatedAppDiaryRouteImport } from './routes/_authenticated/app.diary'
import { Route as AuthenticatedAppDictationRouteImport } from './routes/_authenticated/app.dictation'
import { Route as AuthenticatedAppDocumentsRouteImport } from './routes/_authenticated/app.documents'
import { Route as AuthenticatedAppDraftingRouteImport } from './routes/_authenticated/app.drafting'
import { Route as AuthenticatedAppInsightsRouteImport } from './routes/_authenticated/app.insights'
import { Route as AuthenticatedAppMenuRouteImport } from './routes/_authenticated/app.menu'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppSubscriptionRouteImport } from './routes/_authenticated/app.subscription'
import { Route as AuthenticatedAppTeamRouteImport } from './routes/_authenticated/app.team'
import { Route as AdminAdminSettingsIntegrationsRouteImport } from './routes/_admin/admin.settings.integrations'
import { Route as AuthenticatedAppCasesIndexRouteImport } from './routes/_authenticated/app.cases.index'
import { Route as AuthenticatedAppCasesMatterIdRouteImport } from './routes/_authenticated/app.cases.$matterId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAuditLogRoute = AdminAdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCauseListSourcesRoute =
  AdminAdminCauseListSourcesRouteImport.update({
    id: '/cause-list-sources',
    path: '/cause-list-sources',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminContactRequestsRoute =
  AdminAdminContactRequestsRouteImport.update({
    id: '/contact-requests',
    path: '/contact-requests',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAssistantRoute =
  AuthenticatedAppAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAuditLogRoute =
  AuthenticatedAppAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCasesRoute = AuthenticatedAppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCauseListRoute =
  AuthenticatedAppCauseListRouteImport.update({
    id: '/cause-list',
    path: '/cause-list',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClientsRoute = AuthenticatedAppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDiaryRoute = AuthenticatedAppDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDictationRoute =
  AuthenticatedAppDictationRouteImport.update({
    id: '/dictation',
    path: '/dictation',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentsRoute =
  AuthenticatedAppDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDraftingRoute =
  AuthenticatedAppDraftingRouteImport.update({
    id: '/drafting',
    path: '/drafting',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInsightsRoute =
  AuthenticatedAppInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMenuRoute = AuthenticatedAppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSubscriptionRoute =
  AuthenticatedAppSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTeamRoute = AuthenticatedAppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AdminAdminSettingsIntegrationsRoute =
  AdminAdminSettingsIntegrationsRouteImport.update({
    id: '/settings/integrations',
    path: '/settings/integrations',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AuthenticatedAppCasesIndexRoute =
  AuthenticatedAppCasesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppCasesRoute,
  } as any)
const AuthenticatedAppCasesMatterIdRoute =
  AuthenticatedAppCasesMatterIdRouteImport.update({
    id: '/$matterId',
    path: '/$matterId',
    getParentRoute: () => AuthenticatedAppCasesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/admin/audit-log': typeof AdminAdminAuditLogRoute
  '/admin/cause-list-sources': typeof AdminAdminCauseListSourcesRoute
  '/admin/contact-requests': typeof AdminAdminContactRequestsRoute
  '/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/app/audit-log': typeof AuthenticatedAppAuditLogRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/cases': typeof AuthenticatedAppCasesRouteWithChildren
  '/app/cause-list': typeof AuthenticatedAppCauseListRoute
  '/app/clients': typeof AuthenticatedAppClientsRoute
  '/app/diary': typeof AuthenticatedAppDiaryRoute
  '/app/dictation': typeof AuthenticatedAppDictationRoute
  '/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/app/drafting': typeof AuthenticatedAppDraftingRoute
  '/app/insights': typeof AuthenticatedAppInsightsRoute
  '/app/menu': typeof AuthenticatedAppMenuRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/admin/settings/integrations': typeof AdminAdminSettingsIntegrationsRoute
  '/app/cases/$matterId': typeof AuthenticatedAppCasesMatterIdRoute
  '/app/cases/': typeof AuthenticatedAppCasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/audit-log': typeof AdminAdminAuditLogRoute
  '/admin/cause-list-sources': typeof AdminAdminCauseListSourcesRoute
  '/admin/contact-requests': typeof AdminAdminContactRequestsRoute
  '/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/app/audit-log': typeof AuthenticatedAppAuditLogRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/cause-list': typeof AuthenticatedAppCauseListRoute
  '/app/clients': typeof AuthenticatedAppClientsRoute
  '/app/diary': typeof AuthenticatedAppDiaryRoute
  '/app/dictation': typeof AuthenticatedAppDictationRoute
  '/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/app/drafting': typeof AuthenticatedAppDraftingRoute
  '/app/insights': typeof AuthenticatedAppInsightsRoute
  '/app/menu': typeof AuthenticatedAppMenuRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/admin': typeof AdminAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/admin/settings/integrations': typeof AdminAdminSettingsIntegrationsRoute
  '/app/cases/$matterId': typeof AuthenticatedAppCasesMatterIdRoute
  '/app/cases': typeof AuthenticatedAppCasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/_admin/admin/audit-log': typeof AdminAdminAuditLogRoute
  '/_admin/admin/cause-list-sources': typeof AdminAdminCauseListSourcesRoute
  '/_admin/admin/contact-requests': typeof AdminAdminContactRequestsRoute
  '/_authenticated/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/_authenticated/app/audit-log': typeof AuthenticatedAppAuditLogRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/cases': typeof AuthenticatedAppCasesRouteWithChildren
  '/_authenticated/app/cause-list': typeof AuthenticatedAppCauseListRoute
  '/_authenticated/app/clients': typeof AuthenticatedAppClientsRoute
  '/_authenticated/app/diary': typeof AuthenticatedAppDiaryRoute
  '/_authenticated/app/dictation': typeof AuthenticatedAppDictationRoute
  '/_authenticated/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/_authenticated/app/drafting': typeof AuthenticatedAppDraftingRoute
  '/_authenticated/app/insights': typeof AuthenticatedAppInsightsRoute
  '/_authenticated/app/menu': typeof AuthenticatedAppMenuRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/_authenticated/app/team': typeof AuthenticatedAppTeamRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_admin/admin/settings/integrations': typeof AdminAdminSettingsIntegrationsRoute
  '/_authenticated/app/cases/$matterId': typeof AuthenticatedAppCasesMatterIdRoute
  '/_authenticated/app/cases/': typeof AuthenticatedAppCasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/admin'
    | '/app'
    | '/invite/$token'
    | '/admin/audit-log'
    | '/admin/cause-list-sources'
    | '/admin/contact-requests'
    | '/app/assistant'
    | '/app/audit-log'
    | '/app/billing'
    | '/app/cases'
    | '/app/cause-list'
    | '/app/clients'
    | '/app/diary'
    | '/app/dictation'
    | '/app/documents'
    | '/app/drafting'
    | '/app/insights'
    | '/app/menu'
    | '/app/profile'
    | '/app/subscription'
    | '/app/team'
    | '/admin/'
    | '/app/'
    | '/admin/settings/integrations'
    | '/app/cases/$matterId'
    | '/app/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/invite/$token'
    | '/admin/audit-log'
    | '/admin/cause-list-sources'
    | '/admin/contact-requests'
    | '/app/assistant'
    | '/app/audit-log'
    | '/app/billing'
    | '/app/cause-list'
    | '/app/clients'
    | '/app/diary'
    | '/app/dictation'
    | '/app/documents'
    | '/app/drafting'
    | '/app/insights'
    | '/app/menu'
    | '/app/profile'
    | '/app/subscription'
    | '/app/team'
    | '/admin'
    | '/app'
    | '/admin/settings/integrations'
    | '/app/cases/$matterId'
    | '/app/cases'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/_admin/admin'
    | '/_authenticated/app'
    | '/invite/$token'
    | '/_admin/admin/audit-log'
    | '/_admin/admin/cause-list-sources'
    | '/_admin/admin/contact-requests'
    | '/_authenticated/app/assistant'
    | '/_authenticated/app/audit-log'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/cases'
    | '/_authenticated/app/cause-list'
    | '/_authenticated/app/clients'
    | '/_authenticated/app/diary'
    | '/_authenticated/app/dictation'
    | '/_authenticated/app/documents'
    | '/_authenticated/app/drafting'
    | '/_authenticated/app/insights'
    | '/_authenticated/app/menu'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/subscription'
    | '/_authenticated/app/team'
    | '/_admin/admin/'
    | '/_authenticated/app/'
    | '/_admin/admin/settings/integrations'
    | '/_authenticated/app/cases/$matterId'
    | '/_authenticated/app/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/audit-log': {
      id: '/_admin/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAdminAuditLogRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/cause-list-sources': {
      id: '/_admin/admin/cause-list-sources'
      path: '/cause-list-sources'
      fullPath: '/admin/cause-list-sources'
      preLoaderRoute: typeof AdminAdminCauseListSourcesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/contact-requests': {
      id: '/_admin/admin/contact-requests'
      path: '/contact-requests'
      fullPath: '/admin/contact-requests'
      preLoaderRoute: typeof AdminAdminContactRequestsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/assistant': {
      id: '/_authenticated/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AuthenticatedAppAssistantRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/audit-log': {
      id: '/_authenticated/app/audit-log'
      path: '/audit-log'
      fullPath: '/app/audit-log'
      preLoaderRoute: typeof AuthenticatedAppAuditLogRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cases': {
      id: '/_authenticated/app/cases'
      path: '/cases'
      fullPath: '/app/cases'
      preLoaderRoute: typeof AuthenticatedAppCasesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cause-list': {
      id: '/_authenticated/app/cause-list'
      path: '/cause-list'
      fullPath: '/app/cause-list'
      preLoaderRoute: typeof AuthenticatedAppCauseListRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/clients': {
      id: '/_authenticated/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AuthenticatedAppClientsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/diary': {
      id: '/_authenticated/app/diary'
      path: '/diary'
      fullPath: '/app/diary'
      preLoaderRoute: typeof AuthenticatedAppDiaryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dictation': {
      id: '/_authenticated/app/dictation'
      path: '/dictation'
      fullPath: '/app/dictation'
      preLoaderRoute: typeof AuthenticatedAppDictationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/documents': {
      id: '/_authenticated/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AuthenticatedAppDocumentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/drafting': {
      id: '/_authenticated/app/drafting'
      path: '/drafting'
      fullPath: '/app/drafting'
      preLoaderRoute: typeof AuthenticatedAppDraftingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/insights': {
      id: '/_authenticated/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AuthenticatedAppInsightsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/menu': {
      id: '/_authenticated/app/menu'
      path: '/menu'
      fullPath: '/app/menu'
      preLoaderRoute: typeof AuthenticatedAppMenuRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/subscription': {
      id: '/_authenticated/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AuthenticatedAppSubscriptionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/team': {
      id: '/_authenticated/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AuthenticatedAppTeamRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_admin/admin/settings/integrations': {
      id: '/_admin/admin/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/admin/settings/integrations'
      preLoaderRoute: typeof AdminAdminSettingsIntegrationsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_authenticated/app/cases/': {
      id: '/_authenticated/app/cases/'
      path: '/'
      fullPath: '/app/cases/'
      preLoaderRoute: typeof AuthenticatedAppCasesIndexRouteImport
      parentRoute: typeof AuthenticatedAppCasesRoute
    }
    '/_authenticated/app/cases/$matterId': {
      id: '/_authenticated/app/cases/$matterId'
      path: '/$matterId'
      fullPath: '/app/cases/$matterId'
      preLoaderRoute: typeof AuthenticatedAppCasesMatterIdRouteImport
      parentRoute: typeof AuthenticatedAppCasesRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminAuditLogRoute: typeof AdminAdminAuditLogRoute
  AdminAdminCauseListSourcesRoute: typeof AdminAdminCauseListSourcesRoute
  AdminAdminContactRequestsRoute: typeof AdminAdminContactRequestsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminSettingsIntegrationsRoute: typeof AdminAdminSettingsIntegrationsRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminAuditLogRoute: AdminAdminAuditLogRoute,
  AdminAdminCauseListSourcesRoute: AdminAdminCauseListSourcesRoute,
  AdminAdminContactRequestsRoute: AdminAdminContactRequestsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminSettingsIntegrationsRoute: AdminAdminSettingsIntegrationsRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthenticatedAppCasesRouteChildren {
  AuthenticatedAppCasesMatterIdRoute: typeof AuthenticatedAppCasesMatterIdRoute
  AuthenticatedAppCasesIndexRoute: typeof AuthenticatedAppCasesIndexRoute
}

const AuthenticatedAppCasesRouteChildren: AuthenticatedAppCasesRouteChildren = {
  AuthenticatedAppCasesMatterIdRoute: AuthenticatedAppCasesMatterIdRoute,
  AuthenticatedAppCasesIndexRoute: AuthenticatedAppCasesIndexRoute,
}

const AuthenticatedAppCasesRouteWithChildren =
  AuthenticatedAppCasesRoute._addFileChildren(
    AuthenticatedAppCasesRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAssistantRoute: typeof AuthenticatedAppAssistantRoute
  AuthenticatedAppAuditLogRoute: typeof AuthenticatedAppAuditLogRoute
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppCasesRoute: typeof AuthenticatedAppCasesRouteWithChildren
  AuthenticatedAppCauseListRoute: typeof AuthenticatedAppCauseListRoute
  AuthenticatedAppClientsRoute: typeof AuthenticatedAppClientsRoute
  AuthenticatedAppDiaryRoute: typeof AuthenticatedAppDiaryRoute
  AuthenticatedAppDictationRoute: typeof AuthenticatedAppDictationRoute
  AuthenticatedAppDocumentsRoute: typeof AuthenticatedAppDocumentsRoute
  AuthenticatedAppDraftingRoute: typeof AuthenticatedAppDraftingRoute
  AuthenticatedAppInsightsRoute: typeof AuthenticatedAppInsightsRoute
  AuthenticatedAppMenuRoute: typeof AuthenticatedAppMenuRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppSubscriptionRoute: typeof AuthenticatedAppSubscriptionRoute
  AuthenticatedAppTeamRoute: typeof AuthenticatedAppTeamRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAssistantRoute: AuthenticatedAppAssistantRoute,
  AuthenticatedAppAuditLogRoute: AuthenticatedAppAuditLogRoute,
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppCasesRoute: AuthenticatedAppCasesRouteWithChildren,
  AuthenticatedAppCauseListRoute: AuthenticatedAppCauseListRoute,
  AuthenticatedAppClientsRoute: AuthenticatedAppClientsRoute,
  AuthenticatedAppDiaryRoute: AuthenticatedAppDiaryRoute,
  AuthenticatedAppDictationRoute: AuthenticatedAppDictationRoute,
  AuthenticatedAppDocumentsRoute: AuthenticatedAppDocumentsRoute,
  AuthenticatedAppDraftingRoute: AuthenticatedAppDraftingRoute,
  AuthenticatedAppInsightsRoute: AuthenticatedAppInsightsRoute,
  AuthenticatedAppMenuRoute: AuthenticatedAppMenuRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppSubscriptionRoute: AuthenticatedAppSubscriptionRoute,
  AuthenticatedAppTeamRoute: AuthenticatedAppTeamRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
